name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t hello-world-app .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy test step
        run: echo "Tests would run here (add later)"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d ds2-HelloWorld ]; then
              git clone https://github.com/Nimisha-fh/ds2-HelloWorld.git
            fi
            cd ds2-HelloWorld
            git pull origin main
            docker-compose down || true
            docker-compose up -d --build
